SELECT * FROM DEPARTMENTS;

SELECT e.FIRST_NAME, e.PHONE_NUMBER, e.HIRE_DATE ,e.SALARY  FROM EMPLOYEES e;

SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY , e.PHONE_NUMBER  FROM EMPLOYEES e ;

SELECT e.EMPLOYEE_ID empNo, e.FIRST_NAME "E-mail", e.SALARY "연 봉"
FROM EMPLOYEES e ;

SELECT e.FIRST_NAME || ' hire date is ' || e.HIRE_DATE  FROM EMPLOYEES e ;

SELECT FIRST_NAME, SALARY 
FROM EMPLOYEES e 
WHERE SALARY >= 15000;


SELECT first_name,
		LPAD(FIRST_name, 10, '*'),
		RPAD(first_name, 10, '*') 
FROM EMPLOYEES;
		
SELECT SYSDATE 
FROM dual;

SELECT first_name,
		lpad(first_name, 10, '*'),
		rpad(first_name, 10, '*')
FROM employees;

SELECT *
FROM EMPLOYEES e ;

select count(*), sum(SALARY), avg(SALARY)
from EMPLOYEES
where SALARY>16000;

select DEPARTMENT_ID, sum(SALARY), count(*)
from EMPLOYEES
group by DEPARTMENT_ID;

select DEPARTMENT_id, count(*), sum(SALARY)
from EMPLOYEES
group by DEPARTMENT_ID
having sum(SALARY)>20000
and DEPARTMENT_ID = 100;

select EMPLOYEE_ID, SALARY,
        case when JOB_ID = 'AC_ACCOUNT' then salary + SALARY*0.1
            when JOB_ID = 'AC_MGA' then SALARY + SALARY*0.2
            else SALARY
        end JOB_ID
from EMPLOYEES;

-- 문제1
select e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME, m.FIRST_NAME
from EMPLOYEES e, DEPARTMENTS d, EMPLOYEES m
where e.DEPARTMENT_ID = d.DEPARTMENT_ID
and e.MANAGER_ID = m.EMPLOYEE_ID;

-- 문제2
SELECT r.REGION_NAME, c.COUNTRY_NAME
from REGIONS r, COUNTRIES c
where r.REGION_ID = c.REGION_ID
order by r.REGION_ID DESC, C.COUNTRY_ID DESC;

-- 문제3
SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME, e.FIRST_NAME, l.CITY, c.COUNTRY_NAME, r.REGION_NAME
FROM DEPARTMENTS d, EMPLOYEES e, REGIONS r, LOCATIONS L, COUNTRIES c
where d.DEPARTMENT_ID = e.DEPARTMENT_ID
and r.REGION_ID = c.REGION_ID
and L.COUNTRY_ID = c.COUNTRY_ID;


-- 문제4



-- -- 문제5
-- SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_name
-- FROM EMPLOYEES e, DEPARTMENTS d
-- where e.DEPARTMENT_ID = d.DEPARTMENT_ID
-- ORDER BY e.LAST_NAME;

-- -- 문제6
-- SELECT e.EMPLOYEE_ID, e.LAST_NAME, e.HIRE_DATE
-- FROM EMPLOYEES e, EMPLOYEES m
-- WHERE E.MANAGER_ID = M.EMPLOYEE_ID
-- and E.HIRE_DATE < M.HIRE_DATE;